done=document.querySelector(".done");
box1=document.querySelector(".b1");
f1=document.querySelector(".f1");
i1=document.querySelectorAll(".i1");
f1.addEventListener("submit",(event)=>{
    event.preventDefault();
    console.log("Submitted");
    box1.classList.remove("b1");
    box1.classList.add("b11");
    done.classList.remove("done");
    done.classList.add("done1");
    i1.forEach((input)=>{
        input.disabled=true;
    })
})
box2=document.querySelector(".b2");
f2=document.querySelector(".f2");
done2=document.querySelector(".done2");
i2=document.querySelectorAll(".i2");
f2.addEventListener("submit",(event)=>{
    event.preventDefault();
    console.log("Submitted");
    box2.classList.remove("b2");
    box2.classList.add("b22");
    done2.classList.remove("done2");
    done2.classList.add("done3");
    window.scrollBy(0,window.innerHeight);
    i2.forEach((input)=>{
        input.disabled=true;
    })
})
done4=document.querySelector(".done4");
box3=document.querySelector(".b3");
f3=document.querySelector(".f3");
i3=document.querySelectorAll(".i3");
f3.addEventListener("submit",(event)=>{
    event.preventDefault();
    console.log("Submitted");
    box3.classList.remove("b3");
    box3.classList.add("b33");
    done4.classList.remove("done4");
    done4.classList.add("done5");
    i3.forEach((input)=>{
        input.disabled=true;
    })
})
i4=document.querySelectorAll(".i4");
done6=document.querySelector(".done6");
box4=document.querySelector(".b4");
f4=document.querySelector(".f4");
f4.addEventListener("submit",(event)=>{
    event.preventDefault();
    console.log("Submitted");
    box4.classList.remove("b4");
    box4.classList.add("b44");
    window.scrollBy(0,window.innerHeight);
    done6.classList.remove("done6");
    done6.classList.add("done7");
    i4.forEach((input)=>{
        input.disabled=true;
    })
})
i5=document.querySelectorAll(".i5");
done8=document.querySelector(".done8");
box5=document.querySelector(".b5");
f5=document.querySelector(".f5");
f5.addEventListener("submit",(event)=>{
    event.preventDefault();
    console.log("Submitted");
    box5.classList.remove("b5");
    box5.classList.add("b55");
    done8.classList.remove("done8");
    done8.classList.add("done9");
    i5.forEach((input)=>{
        input.disabled=true;
    })
})
done10=document.querySelector(".done10");
box6=document.querySelector(".b6");
f6=document.querySelector(".f6");
i6=document.querySelectorAll(".i6");
f6.addEventListener("submit",(event)=>{
    event.preventDefault();
    console.log("Submitted");
    box6.classList.remove("b6");
    box6.classList.add("b66");
    window.scrollBy(0,window.innerHeight);
    done10.classList.remove("done10");
    done10.classList.add("done11");
    i6.forEach((input)=>{
        input.disabled=true;
    })
})
i7=document.querySelectorAll(".i7");
done12=document.querySelector(".done12");
box7=document.querySelector(".b7");
f7=document.querySelector(".f7");
f7.addEventListener("submit",(event)=>{
    event.preventDefault();
    console.log("Submitted");
    box7.classList.remove("b7");
    box7.classList.add("b77");
    done12.classList.remove("done12");
    done12.classList.add("done13");
    i7.forEach((input)=>{
        input.disabled=true;
    })
})
i8=document.querySelectorAll(".i8");
done14=document.querySelector(".done14");
box8=document.querySelector(".b8");
f8=document.querySelector(".f8");
f8.addEventListener("submit",(event)=>{
    event.preventDefault();
    console.log("Submitted");
    box8.classList.remove("b8");
    box8.classList.add("b88");
    window.scrollBy(0,window.innerHeight);
    done14.classList.remove("done14");
    done14.classList.add("done15");
    i8.forEach((input)=>{
        input.disabled=true;
    })
})
i9=document.querySelectorAll(".i9");
done16=document.querySelector(".done16");
box9=document.querySelector(".b9");
f9=document.querySelector(".f9");
f9.addEventListener("submit",(event)=>{
    event.preventDefault();
    console.log("Submitted");
    box9.classList.remove("b9");
    box9.classList.add("b99");
    done16.classList.remove("done16");
    done16.classList.add("done17");
    i9.forEach((input)=>{
        input.disabled=true;
    })
})
done18=document.querySelector(".done18");
box10=document.querySelector(".b10");
f10=document.querySelector(".f10");
i10=document.querySelectorAll(".i10");
f10.addEventListener("submit",(event)=>{
    event.preventDefault();
    console.log("Submitted");
    box10.classList.remove("b10");
    box10.classList.add("b101");
    done18.classList.remove("done18");
    done18.classList.add("done19");
    i10.forEach((input)=>{
        input.disabled=true;
    })
})